#define MAJOR 2
#define MINOR 7
#define PATCH 6
#define BUILD 877

// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR##.##MINOR##.##PATCH##.##BUILD
